### ISSUE TITLE
安卓 听歌时拔下耳机直接闪退了

### ISSUE THREAD

**Issue by gelhimother** [listen1/listen1_mobile#10]
听歌的时候直接拔下耳机，安卓版本的客户端就会闪退
以下是安卓9的闪退错误记录，希望能帮到大家。
https://del.dog/iwazegazaw

**Comment by listen1** [comment]
相关修复 https://github.com/listen1/listen1_mobile/commit/95a5dee3ee4bcfc8647bfd8ab34519d3a2a9c8c3 请等待打包，感谢反馈
