### ISSUE TITLE
怎么导入PC端的歌单

### ISSUE THREAD

**Issue by chengwq0** [listen1/listen1_mobile#104]
如何把PC端的歌单导入到Mobile

**Comment by michaelsara** [comment]
> 如何把PC端的歌单导入到Mobile

目前手机端是导出文本文件备份，和电脑端的json文件备份内容看着一致，把电脑端json文件在手机端打开，然后粘贴还原试下

我遇到的是另外一个问题，希望手机端导入倒电脑端：
因为歌曲太多，导致手机端备份需要粘贴文字过多，超过了粘贴板的缓冲大小，所以没办法全面备份，估计如果你电脑端歌单歌曲比较多，导入也会有这个问题
期待手机端备份也支持导出json，和电脑端同步，这样两个终端同步就没问题了

**Comment by cheng-yl** [comment]
谢谢老板
