### ISSUE TITLE
Can't play QQ Music, and it will flash back

### ISSUE THREAD

**Issue by AllToBeNice** [listen1/listen1_mobile#11]
Environment: Android 7.1.2
Listen 1: v0.7.4
Description: Can get QQ Music recommendation list and the songs in it normally, but can't play the songs in it . Click play and it will flash back.

**Comment by FunctionXJB** [comment]
安卓9.0，小米note3，miui10，0.7.4，一样的问题

**Comment by listen1** [comment]
Thanks for your report. The problem is fixed in Version 0.7.5. Please download apk from release page.
