### ISSUE TITLE
想体验新版、iOS版的看过来

### ISSUE THREAD

**Issue by fandypeng** [listen1/listen1_mobile#122]
listen1桌面版和chrome插件版本一直在更新和维护，但是listen1_mobile却没人维护了，已经落后主线分支很远了，我最近把这个项目fork了下来，升级了最新版本的RN，并且同步了chrome_extension版本的大部分功能，有兴趣体验的可以加我微信：fandy-peng

**Comment by yaycoc** [comment]
求IOS平台的，或者给我们一个连接我们直接下载使用

**Comment by fandypeng** [comment]
> 

iOS需要给我udid，我给你单独打包，所以需要加微信😌

**Comment by yaycoc** [comment]
谢谢哥们，我以为只需要一个安装包就可以了，这样每个人使用还要单独处理一次很是麻烦啊，所以我想等后续的public




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "listen1/listen1_mobile"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月14日(星期一) 上午10:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [listen1/listen1_mobile] 想体验新版、iOS版的看过来 (Issue #122)





   
iOS需要给我udid，我给你单独打包，所以需要加微信😌
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fandypeng** [comment]
> 

@yaycoc 不一定会public，只是个人兴趣弄的小项目

**Comment by penhuowa** [comment]
我有个人证书，只需要一个ipa文件

**Comment by ajie815** [comment]
iOS有了吗

**Comment by yaycoc** [comment]
可以有的，找下发帖的那位哥们，我这边是因为我个人原因没有找那哥们要 哈哈哈




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "listen1/listen1_mobile"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月13日(星期天) 中午11:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [listen1/listen1_mobile] 想体验新版、iOS版的看过来 (Issue #122)





 
iOS有了吗
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Moovgen** [comment]
> 

老哥可以分享一份吗😊

**Comment by Lchen1008** [comment]
加你wx了 ，通过一下老哥

**Comment by insomnia417** [comment]
国内真是无论如何都要恰饭

**Comment by liu7526539** [comment]
> 国内真是无论如何都要恰饭

这话说的。你要是多捐赠点大家不就免费了么

**Comment by zc990320** [comment]
> listen1桌面版和chrome插件版本一直在更新和维护，但是listen1_mobile却没人维护了，已经落后主线分支很远了，我最近把这个项目fork了下来，升级了最新版本的RN，并且同步了chrome_extension版本的大部分功能，有兴趣体验的可以关注：趣听音乐馆
哥们，我想要IOS版的，不会开发
