### ISSUE TITLE
手机版在导入网易云音乐时只显示十首歌

### ISSUE THREAD

**Issue by lzhxdsn** [listen1/listen1_mobile#32]
v0.7.4和v0.7.5在导入网易云歌单时只会显示前十首（QQ音乐没试，因为QQ音乐APP取消了链接分享）

**Comment by caliban511** [comment]
是的，所有歌单都只有10首歌

**Comment by listen1** [comment]
已经在 https://github.com/listen1/listen1_mobile/pull/40 中修复，请等待新版本打包，谢谢反馈
