### ISSUE TITLE
挺好一项目，可惜还是死了。。。

### ISSUE THREAD

**Issue by caliban511** [listen1/listen1_mobile#36]
如题。不知道是不是受到了官方或资方或版权方的压力。

**Comment by listen1** [comment]
冒个泡。其实项目还在，就是贡献者少了所以没怎么更新。欢迎大家踊跃PR。

**Comment by caliban511** [comment]
> 冒个泡。其实项目还在，就是贡献者少了所以没怎么更新。欢迎大家踊跃PR。

大佬好。先把网易云歌单只能看到10首歌的问题解决一下吧，目前这个样子就算分享给别人，人家也不用啊。(づ￣ ³￣)づ
