### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [listen1/listen1_mobile#61]
请问是否可以在 F-Droid 发布？如果可以的话，我会在那边打开一个合并请求。我目前的构建没有遇到困难。

**Comment by listen1** [comment]
非常欢迎协助发布到F-Droid。因为项目人手不够，所以没有精力兼顾这些发布平台，欢迎有识之士帮助Listen1被更多的人所使用。

**Comment by linsui** [comment]
谢谢！已打开[合并请求](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8309)。一些这边需要做的：
1. 添加 fastlane。我稍后会 pr。
2. 目前 versionCode 和  versionName 是固定的。F-Droid 需要一个和 tag 匹配的 versionName，即 0.8.0 。versionCode 需保持递增，否则无法提示更新。
3. 之后需要添加一个新的 tag 包含上述修改

感谢帮助！

**Comment by linsui** [comment]
@listen1 请问是否有计划发布包含上述修改的新版本？

**Comment by listen1** [comment]
抱歉刚看到，我这就发布一个0.8.1的版本包含上述修改的

**Comment by linsui** [comment]
非常感谢！

**Comment by linsui** [comment]
@listen1 Kindly ping 😂

**Comment by listen1** [comment]
@linsui sorry for delay. 0.8.1 has release.
https://github.com/listen1/listen1_mobile/releases/tag/v0.8.1

**Comment by linsui** [comment]
:+1: 非常感谢

**Comment by linsui** [comment]
MR 已合并，大概会在几天后进入 F-Droid 的存储库。 :smile: 检查过程中发现了一个小问题，[一些链接](https://github.com/listen1/listen1_mobile/search?q=http%3A%2F%2F
)使用的是 http, 例如 http://p2.music.126.net/ . 这些链接的 https 可用，所以请将它们改为 https，谢谢!

**Comment by listen1** [comment]
非常感谢。
https的问题会及时修复。

**Comment by linsui** [comment]
已发布 https://f-droid.org/packages/com.listen1.app

可以将这个徽章放在 Readme 中 😄 
```md
[<img src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png"
    alt="Get it on F-Droid"
    height="80">](https://f-droid.org/packages/com.listen1.app)
```

[<img src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png"
    alt="Get it on F-Droid"
    height="80">](https://f-droid.org/packages/com.listen1.app)
